apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.19.0 (f63a961c)
  labels:
    io.kompose.service: s3
  name: s3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.19.0 (f63a961c)
      labels:
        io.kompose.service: s3
        app: s3
    spec:
      containers:
      - env:
        - name: ES_HOST
          valueFrom:
            secretKeyRef:
              name: elasticsearch
              key: host
        - name: LOGSTASH_USER
          valueFrom:
            secretKeyRef:
              name: elasticsearch
              key: logstash-user
        - name: LOGSTASH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elasticsearch
              key: logstash-password
        - name: DB_ENGINE
          valueFrom:
            secretKeyRef:
              name: database
              key: engine
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: database
              key: host
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: database
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database
              key: password
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: database
              key: port
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: database
              key: name
        - name: CONSUMER_SERVER
          valueFrom:
            secretKeyRef:
              name: kafka
              key: consumer-server
        - name: TOPIC_STRATEGY_FORMAT
          valueFrom:
            secretKeyRef:
              name: kafka
              key: topic-strategy-format
        - name: CONSUMER_GROUP_ID
          value: s3_consumer
        - name: STEP_VERSION
          value: s3_0.0.1
        - name: METRICS_HOST
          valueFrom:
            secretKeyRef:
              name: metrics
              key: host
        - name: METRICS_TOPIC
          valueFrom:
            secretKeyRef:
              name: metrics
              key: topic
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws
              key: access-key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws
              key: secret-access-key
        - name: BUCKET_NAME
          value: alerce-ztf-pipeline-integration-test
        - name: REGION_NAME
          value: us-east-1
        image: ghcr.io/alercebroker/s3_step:latest
        name: s3
      restartPolicy: Always
      imagePullSecrets:
      - name: test
    # nodeSelector:
    #   disktype: s3
status: {}
