apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: alert-archiving-step
  name: alert-archiving-step
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: alert-archiving-step
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: alert-archiving-step
    spec:
      containers:
        - env:
            - name: CONSUMER_GROUP_ID
              value: archiving-step
            - name: CONSUMER_SERVER
              valueFrom:
                secretKeyRef:
                  name: kafka
                  key: consumer-server
            - name: TOPIC_STRATEGY_FORMAT
              valueFrom:
                secretKeyRef:
                  name: kafka
                  key: topic-strategy-format
          image: ghcr.io/alercebroker/alert_archiving_step:rc
          name: alert-archiving-step
          resources: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: pull-permissions
status: {}
