apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f early_classification/docker-compose.yml
    kompose.version: 1.19.0 (f63a96gc)
  labels:
    io.kompose.service: early
  name: early
spec:
  replicas: 8
  selector:
    matchLabels:
      app: early
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f early_classification/docker-compose.yml
        kompose.version: 1.19.0 (f63a96gc)
      labels:
        io.kompose.service: early
        app: early
    spec:
      containers:
      - env:
        - name: ES_HOST
          valueFrom:
            secretKeyRef:
              name: elasticsearch
              key: host
        - name: LOGSTASH_USER
          valueFrom:
            secretKeyRef:
              name: elasticsearch
              key: logstash-user
        - name: LOGSTASH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elasticsearch
              key: logstash-password
        - name: DB_ENGINE
          valueFrom:
            secretKeyRef:
              name: database
              key: engine
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: database
              key: host
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: database
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database
              key: password
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: database
              key: port
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: database
              key: name
        - name: CONSUMER_SERVER
          valueFrom:
            secretKeyRef:
              name: kafka
              key: consumer-server
        - name: TOPIC_STRATEGY_FORMAT
          valueFrom:
            secretKeyRef:
              name: kafka
              key: topic-strategy-format
          #name: CONSUMER_TOPICS
          #value: ztf_20211120_programid1
        - name: CONSUMER_GROUP_ID
          value: early_consumer
        - name: PRODUCER_SERVER
          valueFrom:
            secretKeyRef:
              name: kafka
              key: producer-public-server
        - name: PRODUCER_TOPIC_FORMAT
          value: stamp_classifier_%s
        - name: PRODUCER_DATE_FORMAT
          value: "%Y%m%d"
        - name: PRODUCER_CHANGE_HOUR
          value: "20"
        - name: PRODUCER_RETENTION_DAYS
          value: "1"
        - name: PRODUCER_SECURITY_PROTOCOL
          value: SASL_PLAINTEXT
        - name: PRODUCER_SASL_MECHANISM
          value: "SCRAM-SHA-256"
        - name: PRODUCER_SASL_USERNAME
          valueFrom:
            secretKeyRef:
              name: kafka
              key: stam_step_username
        - name: PRODUCER_SASL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kafka
              key: stam_step_password
        - name: STEP_VERSION
          value: stamp_classifier_1.0.0
        - name : CLASSIFIER_VERSION
          value: stamp_classifier_1.0.4
        - name: METRICS_HOST
          valueFrom:
            secretKeyRef:
              name: metrics
              key: host
        - name: METRICS_TOPIC
          valueFrom:
            secretKeyRef:
              name: metrics
              key: topic
        image: ghcr.io/alercebroker/early_classification_step:latest
        name: early
      restartPolicy: Always
      imagePullSecrets:
      - name: test
   #  nodeSelector:
   #    disktype: early_classification
status: {}
