apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: watchlist
  name: watchlist
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: watchlist
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: watchlist
    spec:
      containers:
        - env:
            - name: ALERTS_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: alerts-database
                  key: host
            - name: ALERTS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: alerts-database
                  key: name
            - name: ALERTS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: alerts-database
                  key: password
            - name: ALERTS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: alerts-database
                  key: user
            - name: CONSUMER_GROUP_ID
              value: watchlist_consumer_k8
            - name: CONSUMER_SERVER
              valueFrom:
                secretKeyRef:
                  name: kafka
                  key: consumer-server
            - name: TOPIC_STRATEGY_FORMAT
              valueFrom:
                secretKeyRef:
                  name: kafka
                  key: topic-strategy-format
                    #- name: CONSUMER_TOPICS
                    #value: ztf_20211120_programid1
            - name: CONSUME_MESSAGES
              value: "500"
            - name: USERS_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: users-database
                  key: user-db-host
            - name: USERS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: users-database
                  key: name
            - name: USERS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: users-database
                  key: password
            - name: USERS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: users-database
                  key: user
            - name: METRICS_HOST
              valueFrom:
                secretKeyRef:
                  name: metrics
                  key: host
            - name: METRICS_TOPIC
              valueFrom:
                secretKeyRef:
                  name: metrics
                  key: topic
            - name: ES_HOST
              valueFrom:
                secretKeyRef:
                  name: elasticsearch
                  key: host
            - name: LOGSTASH_USER
              valueFrom:
                secretKeyRef:
                  name: elasticsearch
                  key: logstash-user
            - name: LOGSTASH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch
                  key: logstash-password
          image: ghcr.io/alercebroker/watchlist_step:latest
          name: watchlist
          resources: {}
      restartPolicy: Always
      imagePullSecrets:
      - name: image-pull-access
status: {}
