apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: transformer-online-classifier-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: transformer-online-classifier-step
  minReplicas: 1
  maxReplicas: 15
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
