---
{{- if .Values.autoscaling.ztf.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: '{{ include "sorting-hat.fullname" . }}-ztf'
  labels:
    {{- include "sorting-hat.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: '{{ include "sorting-hat.fullname" . }}-ztf'
  minReplicas: {{ .Values.autoscaling.ztf.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.ztf.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.ztf.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.autoscaling.ztf.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.autoscaling.ztf.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.autoscaling.ztf.targetMemoryUtilizationPercentage }}
    {{- end }}
    {{- if .Values.autoscaling.ztf.targetConsumedMessages}}
    - type: Pods
      pods:
        metric:
          name: consumed_messages
        target:
          type: Value
          averageValue: 200
    {{- end}}
{{- end }}
---
{{- if .Values.autoscaling.atlas.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: '{{ include "sorting-hat.fullname" . }}-atlas'
  labels:
    {{- include "sorting-hat.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: '{{ include "sorting-hat.fullname" . }}-atlas'
  minReplicas: {{ .Values.autoscaling.atlas.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.atlas.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.atlas.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.autoscaling.atlas.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.autoscaling.atlas.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.autoscaling.atlas.targetMemoryUtilizationPercentage }}
    {{- end }}
    {{- if .Values.autoscaling.ztf.targetConsumedMessages}}
    - type: Pods
      pods:
        metric:
          name: consumed_messages
        target:
          type: Value
          averageValue: 200
    {{- end}}
{{- end }}