---
apiVersion: v1
kind: Service
metadata:
  name: '{{ include "sorting-hat.fullname" . }}-ztf'
  labels:
    {{- include "sorting-hat.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sorting-hat.selectorLabels" . | nindent 4 }}
---
---
apiVersion: v1
kind: Service
metadata:
  name: '{{ include "sorting-hat.fullname" . }}-atlas'
  labels:
    {{- include "sorting-hat.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sorting-hat.selectorLabels" . | nindent 4 }}