apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prv-candidates.fullname" . }}
  namespace: {{ .Values.namespace }}
data:
  consumer-topics: {{ .Values.configmap.consumerTopics }}
  consume-messages: "{{ .Values.configmap.consumeMessages }}"
  internal-server: {{ .Values.configmap.internalServer }}
  scribe-topic: {{ .Values.configmap.scribeTopic }}
  producer-topic: {{ .Values.configmap.producerTopic }}
  metrics-topic: {{ .Values.configmap.metricsTopic }}
