apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prv-candidates.fullname" . }}
  namespace: {{ .Values.namespace }}
data:
  class-prefix: {{ .Values.configmap.classPrefix }}
  consumer-topics: {{ .Values.configmap.consumerTopics }}
  consume-messages: "{{ .Values.configmap.consumeMessages }}"
  consumer-server: {{ .Values.configmap.consumerServer }}
  consumer-group-id: {{ .Values.configmap.consumerGroupId | default (printf "%s" (include "prv-candidates.fullname" .)) }}
  scribe-server: {{ .Values.configmap.scribeServer }}
  scribe-topic: {{ .Values.configmap.scribeTopic }}
  producer-server: {{ .Values.configmap.producerServer }}
  producer-topic: {{ .Values.configmap.producerTopic }}
  producer-message-max-bytes: "{{ .Values.configmap.producerMessageMaxBytes }}"
  metrics-server: {{ .Values.configmap.metricsServer }}
  metrics-topic: {{ .Values.configmap.metricsTopic }}
