apiVersion: v1
kind: Secret
metadata:
  name: kafka
  namespace: pipeline
stringData:
  # Comma separated kafka brokers to consume (example: kafka1:9092, kafka2:9092, kafka3:9092)
  consumer-server: ""
  # Topic strategy used in daily topic change (example: ztf_%s_programid1)
  topic-strategy-format: ""
  # Comma separated kafka brokers to produce (example: kafka1:9092, kafka2:9092, kafka3:9092)
  producer-server: ""
  producer-public-server: ""
  # Stamp classifier kafka authentication
  stamp_step_username: ""
  stamp_step_password: ""
  # LC classifier kafka authentication
  lc_step_username: ""
  lc_step_password: ""
