---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "watchlist-step.fullname" . }}
  namespace: {{ .Values.namespace }}
data:
  consumer-topics: {{ .Values.configmap.consumerTopics }}
  internal-server: {{ .Values.configmap.internalServer }}
  metrics-topic: {{ .Values.configmap.metricsTopic }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alerts-database
  namespace: {{ .Values.namespace }}
data:
  host: {{ .Values.configmap.alertsDb.host }}
  name: {{ .Values.configmap.alertsDb.name }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: users-database
  namespace: {{ .Values.namespace }}
data:
  host: {{ .Values.configmap.usersDb.host }}
  name: {{ .Values.configmap.usersDb.name }}