apiVersion: v1
kind: Secret
metadata:
  name: {{ include "logstash.fullname" . }}
  namespace: {{ .Values.namespace }}
stringData:
  username: {{ .Values.secrets.username }}
  password: {{ .Values.secrets.password }}