---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "logstash.fullname" . }}
  namespace: {{ .Values.namespace }}
stringData:
  username: {{ .Values.secrets.elasticsearch.username }}
  password: {{ .Values.secrets.elasticsearch.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: kafka-auth
  namespace: {{ .Values.namespace }}
stringData:
  username: "{{ .Values.secrets.kafkaAuth.username }}"
  password: "{{ .Values.secrets.kafkaAuth.password }}"