apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "early-classifier.fullname" . }}
  namespace: {{ .Values.namespace }}
data:
  consumer-topics: {{ .Values.configmap.consumerTopics }}
  internal-server: {{ .Values.configmap.internalServer }}
  public-server: {{ .Values.configmap.publicServer }}
  producer-topic-format: {{ .Values.configmap.producerTopicFormat }}
  producer-date-format: "{{ .Values.configmap.producerDateFormat }}"
  producer-change-hour: "{{ .Values.configmap.producerChangeHour }}"
  metrics-topic: {{ .Values.configmap.metricsTopic }}
  classifier-version: {{ .Values.configmap.classifierVersion }}