apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "early-classifier.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "early-classifier.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "early-classifier.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "early-classifier.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: 8000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: CONSUMER_TOPICS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "early-classifier.fullname" . }}
                  key: consumer-topics
            - name: CONSUMER_SERVER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "early-classifier.fullname" . }}
                  key: internal-server
            - name: CONSUMER_GROUP_ID
              value: {{ include "early-classifier.fullname" . }}
            - name: PRODUCER_SERVER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "early-classifier.fullname" . }}
                  key: public-server
            - name: PRODUCER_SASL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kafka-auth
                  key: producer-username
            - name: PRODUCER_SASL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-auth
                  key: producer-password
            - name: PRODUCER_TOPIC_FORMAT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "early-classifier.fullname" . }}
                  key: producer-topic-format
            - name: PRODUCER_DATE_FORMAT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "early-classifier.fullname" . }}
                  key: producer-date-format
            - name: PRODUCER_CHANGE_HOUR
              valueFrom:
                configMapKeyRef:
                  name: {{ include "early-classifier.fullname" . }}
                  key: producer-change-hour
            - name: PRODUCER_RETENTION_DAYS
              value: "1"
            - name: METRICS_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "early-classifier.fullname" . }}
                  key: internal-server
            - name: METRICS_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: {{ include "early-classifier.fullname" . }}
                  key: metrics-topic
            {{- if .Values.secrets.kafkaAuth.enabled }}
            - name: KAFKA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kafka-auth
                  key: username
            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-auth
                  key: password
            {{- end }}
            - name: STEP_VERSION
              value: {{ .Chart.AppVersion }}
            - name: CLASSIFIER_VERSION
              valueFrom:
                configMapKeyRef:
                  name: {{ include "early-classifier.fullname" . }}
                  key: classifier-version
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: host
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: port
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: name
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
