apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "elasticc-simulator.fullname" . }}
  namespace: {{ .Values.namespace }}
data:
  internal-server: {{ .Values.configmap.internalServer }}
  producer-topic: {{ .Values.configmap.producerTopic }}