apiVersion: v1
kind: Secret
metadata:
  name: kafka-auth
  namespace: {{ .Values.namespace }}
stringData:
  username: {{ .Values.secrets.kafkaAuth.username }}
  password: {{ .Values.secrets.kafkaAuth.password }}
  metrics-username: {{ .Values.secrets.metricsKafkaAuth.username }}
  metrics-password: {{ .Values.secrets.metricsKafkaAuth.password }}