apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.19.0 (f63a961c)
  labels:
    io.kompose.service: correction
  name: correction
spec:
  replicas: 2
  selector:
    matchLabels:
      app: correction
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.19.0 (f63a961c)
      labels:
        io.kompose.service: correction
        app: correction
    spec:
      containers:
      - env:
        - name: ES_HOST
          valueFrom:
            secretKeyRef:
              name: elasticsearch
              key: host
        - name: LOGSTASH_USER
          valueFrom:
            secretKeyRef:
              name: elasticsearch
              key: logstash-user
        - name: LOGSTASH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elasticsearch
              key: logstash-password
        - name: DB_ENGINE
          valueFrom:
            secretKeyRef:
              name: alerts-database
              key: engine
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: alerts-database
              key: host
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: alerts-database
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: alerts-database
              key: password
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: alerts-database
              key: port
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: alerts-database
              key: name
        - name: CONSUMER_SERVER
          valueFrom:
            secretKeyRef:
              name: kafka
              key: consumer-server
        - name: CONSUMER_TOPICS
          value: xmatch
        - name: CONSUMER_GROUP_ID
          value: correction_consumer
        - name: PRODUCER_SERVER
          valueFrom:
            secretKeyRef:
              name: kafka
              key: producer-server
        - name: PRODUCER_TOPIC
          value: correction
        - name: STEP_ID
          value: correction_1.0.6
        - name: STEP_VERSION
          value: correction_1.0.6
        - name: METRICS_HOST
          valueFrom:
            secretKeyRef:
              name: metrics
              key: host
        - name: METRICS_TOPIC
          valueFrom:
            secretKeyRef:
              name: metrics
              key: topic
        - name: CONSUME_TIMEOUT
          value: "5"
        - name: CONSUME_MESSAGES
          value: "100"
        image: ghcr.io/alercebroker/preprocess_step:latest
        name: correction
      restartPolicy: Always
      imagePullSecrets:
      - name: image-pull-access
    # nodeSelector:
    #   disktype: preprocess
status: {}
