apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-step
spec:
  selector:
    matchLabels:
      app: feature-step
  template:
    metadata:
      labels:
        app: feature-step
    spec:
      containers:
      - env:
        - name: CONSUMER_SERVER
          valueFrom:
            secretKeyRef:
              name: kafka
              key: consumer-server
        - name: CONSUMER_TOPICS
          value: ingestion
        - name: CONSUMER_GROUP_ID
          value: feature_consumer
        - name: PRODUCER_SERVER
          valueFrom:
            secretKeyRef:
              name: kafka
              key: producer-server
        - name: PRODUCER_TOPIC
          value: features
        - name: FEATURE_VERSION
          value: lc_classifier_elasticc
        - name: METRICS_HOST
          valueFrom:
            secretKeyRef:
              name: metrics
              key: host
        - name: METRICS_TOPIC
          valueFrom:
            secretKeyRef:
              name: metrics
              key: topic
        - name: CONSUME_TIMEOUT
          value: "10"
        - name: CONSUME_MESSAGES
          value: "100"
        image: ghcr.io/alercebroker/feature_step:elasticc-a7a61eb
        imagePullPolicy: Always
        name: feature
        resources:
          requests:
            memory: 300M
            cpu: 600m
      restartPolicy: Always
      imagePullSecrets:
      - name: image-pull-access
status: {}
