---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-step-lsst
spec:
  selector:
    matchLabels:
      step: ingestion-step-lsst
  template:
    metadata:
      labels:
        step: ingestion-step-lsst
    spec:
      containers:
        - env:
            - name: CONSUME_MESSAGES
              value: "500"
            - name: CONSUMER_GROUP_ID
              value: ingestion-step-lsst
            - name: CONSUMER_SERVER
              valueFrom:
                secretKeyRef:
                  name: kafka
                  key: consumer-server
            - name: CONSUMER_TOPICS
              value: sorting-hat-lsst
            - name: PRODUCER_SERVER
              valueFrom:
                secretKeyRef:
                  name: kafka
                  key: producer-server
            - name: PRODUCER_TOPIC
              value: ingestion
            - name: MONGO_HOST
              valueFrom:
                secretKeyRef:
                  name: alerts-database-mongo
                  key: host
            - name: MONGO_NAME
              valueFrom:
                secretKeyRef:
                  name: alerts-database-mongo
                  key: database
            - name: MONGO_PORT
              valueFrom:
                secretKeyRef:
                  name: alerts-database-mongo
                  key: port
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: alerts-database-mongo
                  key: user
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: alerts-database-mongo
                  key: password
            - name: METRICS_HOST
              valueFrom:
                secretKeyRef:
                  name: metrics
                  key: host
            - name: METRICS_TOPIC
              valueFrom:
                secretKeyRef:
                  name: metrics
                  key: topic
          image: ghcr.io/alercebroker/ingestion_step:elasticc-99815ec
          imagePullPolicy: Always
          name: ingestion-step-lsst
          resources:
            requests:
              memory: 512M
              cpu: 250m
      restartPolicy: Always
      imagePullSecrets:
        - name: image-pull-access
