apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: correction
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: correction
  minReplicas: 14
  maxReplicas: 14
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10
