apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: early
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: early
  minReplicas: 8 #28
  maxReplicas: 8 #28
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10
