apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: feature
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: feature
  minReplicas: 16 #128
  maxReplicas: 16 #128
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10
