apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: lcclassifier
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lcclassifier
  minReplicas: 2 #28
  maxReplicas: 2 #28
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10
