apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: s3
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: s3
  minReplicas: 0 #28
  maxReplicas: 0 #28
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10
