apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: xmatch
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: xmatch
  minReplicas: 4 
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
