apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-archiving-step
  namespace: pipeline
spec:
  selector:
    matchLabels:
      app: alert-archiving-step
  template:
    metadata:
      labels:
        app: alert-archiving-step
    spec:
      affinity:
        nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                  - matchExpressions:
                    - key: eks.amazonaws.com/nodegroup
                      operator: In
                      values:
                          - staging-pipeline
      containers:
        - env:
            - name: CONSUMER_GROUP_ID
              value: archiving-step
            - name: CONSUMER_SERVER
              valueFrom:
                secretKeyRef:
                  name: kafka
                  key: consumer-server
            - name: CONSUMER_TOPICS
              value: "^ztf*"
            - name: METRICS_HOST
              valueFrom:
                secretKeyRef:
                  name: metrics
                  key: host
            - name: METRICS_TOPIC
              valueFrom:
                secretKeyRef:
                  name: metrics
                  key: topic
            - name: S3_ZTF_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: s3
                  key: grouped-avro
          image: ghcr.io/alercebroker/alert_archiving_step:1.0.0
          name: alert-archiving-step
          resources:
            requests:
              memory: 300M
              cpu: 300m
      restartPolicy: Always
      imagePullSecrets:
        - name: image-pull-access
