apiVersion: apps/v1
kind: Deployment
metadata:
  name: xmatch-step
  namespace: pipeline
spec:
  selector:
    matchLabels:
      app: xmatch-step
  template:
    metadata:
      labels:
        app: xmatch-step
    spec:
      affinity:
        nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                  - matchExpressions:
                    - key: eks.amazonaws.com/nodegroup
                      operator: In
                      values:
                          - staging-pipeline
      containers:
      - env:
        - name: DB_ENGINE
          valueFrom:
            secretKeyRef:
              name: alerts-database
              key: engine
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: alerts-database
              key: host
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: alerts-database
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: alerts-database
              key: password
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: alerts-database
              key: port
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: alerts-database
              key: name
        - name: CONSUMER_SERVER
          valueFrom:
            secretKeyRef:
              name: kafka
              key: consumer-server
        - name: CONSUMER_TOPICS
          value: ingestion
        - name: CONSUMER_GROUP_ID
          value: xmatch-step
        - name: PRODUCER_SERVER
          valueFrom:
            secretKeyRef:
              name: kafka
              key: producer-server
        - name: PRODUCER_TOPIC
          value: xmatch
        - name: STEP_VERSION
          value: xmatch_2.0.0
        - name: METRICS_HOST
          valueFrom:
            secretKeyRef:
              name: metrics
              key: host
        - name: METRICS_TOPIC
          valueFrom:
            secretKeyRef:
              name: metrics
              key: topic
        - name: RETRIES
          value: "3"
        - name: RETRY_INTERVAL
          value: "1"
        - name: CONSUME_TIMEOUT
          value: "5"
        - name: CONSUME_MESSAGES
          value: "1000"
        image: ghcr.io/alercebroker/xmatch_step:latest
        imagePullPolicy: Always
        name: xmatch-step
        resources:
          requests:
            memory: 320M
            cpu: 500m
      restartPolicy: Always
      imagePullSecrets:
      - name: image-pull-access
