---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: log-pipeline
spec:
  spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-pipeline
  template:
    metadata:
      labels:
        app: log-pipeline
    spec:
      hostname: log-pipeline
      containers:
      - name: log-pipeline
        ports:
          - containerPort: 5044
            name: filebeat
          - containerPort: 9600
            name: logstash
        image: docker.elastic.co/logstash/logstash:7.0.0-alpha2
        volumeMounts:
        - name: log-pipeline-config
          mountPath: /usr/share/logstash/pipeline/
        command:
        - logstash
        env:
        - name: ES_HOST
          valueFrom:
            secretKeyRef:
              name: elasticsearch
              key: host
        - name: LOGSTASH_USER
          valueFrom:
            secretKeyRef:
              name: elasticsearch
              key: filebeat-user
        - name: LOGSTASH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elasticsearch
              key: filebeat-user
        - name: CONSUMER_SERVER
          valueFrom:
            secretKeyRef:
              name: metrics
              key: host
        - name: METRICS_TOPIC
          valueFrom:
            secretKeyRef:
              name: metrics
              key: topic

      volumes:
      - name: log-pipeline-config
        configMap:
          name: log-pipeline
          items:
          - key: log-pipeline-es.conf
            path: log-pipeline-es.conf
---
kind: Service
apiVersion: v1
metadata:
  name: log-pipeline
spec:
  type: NodePort
  selector:
    app: log-pipeline
  ports:
  - protocol: TCP
    port: 5044
    targetPort: 5044
    nodePort: 30102
    name: filebeat
  - protocol: TCP
    port: 9600
    targetPort: 9600
    name: logstash
---
