apiVersion: v1
kind: Secret
metadata:
  name: '{{ include "chart.fullname" . }}-kafka'
  namespace: {{ .Values.namespace }}
stringData:
  username: {{ .Values.secrets.kafka.username }}
  password: {{ .Values.secrets.kafka.password }}