apiVersion: v1
kind: Service
metadata:
  name: '{{ include "chart.fullname" . }}-atlas'
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.atlas.type }}
  ports:
    - port: {{ .Values.service.atlas.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: '{{ include "chart.name" . }}-atlas'
    app.kubernetes.io/instance: {{ .Release.Name }}