apiVersion: v1
kind: Secret
#Postgresql Database information
metadata:
  name: users-database
stringData:
  #Engine currently is only postgresql
  user-db-host: ***REMOVED***
  user: "users_api"
  password: ***REMOVED***
  name: "users"
