---
apiVersion: v1
kind: Service
metadata:
  name: '{{ include "ingestion-step.fullname" . }}-atlas'
  labels:
    {{- include "ingestion-step.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: '{{ include "ingestion-step.name" . }}-atlas'
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: '{{ include "ingestion-step.fullname" . }}-ztf'
  labels:
    {{- include "ingestion-step.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: '{{ include "ingestion-step.name" . }}-ztf'
    app.kubernetes.io/instance: {{ .Release.Name }}