---
kind: ConfigMap
apiVersion: v1
metadata:
  name: consolidated-logstash-pipeline
data:
  consolidated-logstash-pipeline-es.conf: |-
    input {
        kafka {
            bootstrap_servers => "${CONSUMER_SERVER}:9092"
            topics =>  ["${METRICS_TOPIC}"]
            codec => "json"
            group_id => "logstash"
            auto_offset_reset => "earliest"
      }
    }
    filter {

    }
    output {
        elasticsearch {
            hosts       => ["${ES_HOST}:9200"]
            user        => "${LOGSTASH_USER:logstash_internal}"
            password    => "${LOGSTASH_PASSWORD:x-pack-test-password}"
            index => "pipeline-consolidated-metrics-%{+YYYY-MM-dd}"
        }
        stdout {
            codec => rubydebug
          }
    }

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: consolidated-logstash-pipeline
spec:
  spec:
  replicas: 1
  selector:
    matchLabels:
      app: consolidated-logstash-pipeline
  template:
    metadata:
      labels:
        app: consolidated-logstash-pipeline
    spec:
      hostname: consolidated-logstash-pipeline
      containers:
      - name: consolidated-logstash-pipeline
        # ports:
        #   - containerPort: 5044
        #     name: filebeat
        #   - containerPort: 9600
        #     name: logstash
        image: docker.elastic.co/logstash/logstash:8.2.0-amd64
        volumeMounts:
        - name: consolidated-logstash-pipeline-config
          mountPath: /usr/share/logstash/pipeline/
        command:
        - logstash
        env:
        - name: MONITORING_ELASTICSEARCH_HOSTS
          valueFrom:
            secretKeyRef:
              name: elasticsearch
              key: host
        - name: ES_HOST
          valueFrom:
            secretKeyRef:
              name: elasticsearch
              key: host
        - name: LOGSTASH_USER
          valueFrom:
            secretKeyRef:
              name: elasticsearch
              key: filebeat-user
        - name: LOGSTASH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elasticsearch
              key: filebeat-password
        - name: CONSUMER_SERVER
          valueFrom:
            secretKeyRef:
              name: metrics
              key: host
        - name: METRICS_TOPIC
          value: consolidated-metrics
      volumes:
      - name: consolidated-logstash-pipeline-config
        configMap:
          name: consolidated-logstash-pipeline
          items:
          - key: consolidated-logstash-pipeline-es.conf
            path: consolidated-logstash-pipeline-es.conf
# ---
# kind: Service
# apiVersion: v1
# metadata:
#   name: consolidated-logstash-pipeline
# spec:
#   type: NodePort
#   selector:
#     app: consolidated-logstash-pipeline
#   ports:
#   - protocol: TCP
#     port: 5044
#     targetPort: 5044
#     nodePort: 30102
#     name: filebeat
#   - protocol: TCP
#     port: 9600
#     targetPort: 9600
#     name: logstash
# ---
