---
apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ include "s3-step.fullname" . }}-atlas'
  namespace: {{ .Values.namespace }}
data:
  consumer-topics: {{ .Values.configmap.atlas.consumerTopics }}
  internal-server: {{ .Values.configmap.atlas.internalServer }}
  metrics-topic: {{ .Values.configmap.atlas.metricsTopic }}
  bucket-name: {{ .Values.configmap.atlas.bucketName }}
  region-name: {{ .Values.configmap.atlas.regionName }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ include "s3-step.fullname" . }}-ztf'
  namespace: {{ .Values.namespace }}
data:
  consumer-topics: {{ .Values.configmap.ztf.consumerTopics }}
  internal-server: {{ .Values.configmap.ztf.internalServer }}
  metrics-topic: {{ .Values.configmap.ztf.metricsTopic }}
  bucket-name: {{ .Values.configmap.ztf.bucketName }}
  region-name: {{ .Values.configmap.ztf.regionName }}