---
kind: ConfigMap
apiVersion: v1
metadata:
  name: logstash-config
  namespace: pipeline
data:
  log-pipeline-es.conf: |-
    input {
        kafka {
            bootstrap_servers => "${CONSUMER_SERVER}:9092"
            topics =>  ["${METRICS_TOPIC}"]
            codec => "json"
            group_id => "logstash"
            auto_offset_reset => "earliest"
      }
    }
    filter {

    }
    output {
        elasticsearch {
            hosts       => ["${ES_HOST}"]
            user        => "${LOGSTASH_USER}"
            password    => "${LOGSTASH_PASSWORD}"
            index => "pipeline-metrics-%{+YYYY-MM-dd}"
        }
    }

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: log-pipeline
  namespace: pipeline
spec:
  spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-pipeline
  template:
    metadata:
      labels:
        app: log-pipeline
    spec:
      hostname: log-pipeline
      affinity:
        nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                  - matchExpressions:
                    - key: eks.amazonaws.com/nodegroup
                      operator: In
                      values:
                          - staging-pipeline
      containers:
      - name: log-pipeline
        ports:
          - containerPort: 5044
            name: filebeat
          - containerPort: 9600
            name: logstash
        image: docker.elastic.co/logstash/logstash-oss:8.6.1-amd64
        volumeMounts:
        - name: log-pipeline-config
          mountPath: /usr/share/logstash/pipeline/
        command:
        - logstash
        env:
        - name: MONITORING_ELASTICSEARCH_HOSTS
          valueFrom:
            secretKeyRef:
              name: elasticsearch
              key: host
        - name: ES_HOST
          valueFrom:
            secretKeyRef:
              name: elasticsearch
              key: host
        - name: LOGSTASH_USER
          valueFrom:
            secretKeyRef:
              name: elasticsearch
              key: logstash-user
        - name: LOGSTASH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elasticsearch
              key: logstash-password
        - name: CONSUMER_SERVER
          valueFrom:
            secretKeyRef:
              name: metrics
              key: host
        - name: METRICS_TOPIC
          valueFrom:
            secretKeyRef:
              name: metrics
              key: topic

      volumes:
      - name: log-pipeline-config
        configMap:
          name: logstash-config
          items:
          - key: log-pipeline-es.conf
            path: log-pipeline-es.conf
